import type { TopicAnalysisResult, TopicSuggestionsResult } from "@/types/topic";

export interface DataIntegrityCheckResult {
  pass: boolean;
  violations: string[];
}

export class AIDataIntegrityService {
  /**
   * Validates AI output to prevent data fabrication, fake statistics, fake citations, and forbidden absolute claims
   */
  static validateTopicOutput(
    output: TopicAnalysisResult | TopicSuggestionsResult,
    knownFacts: Record<string, unknown> = {}
  ): DataIntegrityCheckResult {
    const violations: string[] = [];

    // Extract all text generated by AI
    const allTextParts: string[] = [];

    if (output.action === "analyze_topic") {
      const a = output.analysis;
      Object.values(a).forEach((v) => allTextParts.push(v.comment));
      output.strengths.forEach((s) => allTextParts.push(s));
      output.needsRevision.forEach((n) => allTextParts.push(n));
      output.suggestions.forEach((s) => {
        allTextParts.push(s.title, s.rationale, s.evidenceFeasibility);
      });
    } else if (output.action === "suggest_topics") {
      output.topics.forEach((t) => {
        allTextParts.push(t.title, t.rationale, t.evidenceFeasibility, t.notes);
        t.strengths.forEach((s) => allTextParts.push(s));
      });
      allTextParts.push(output.recommendationReason);
    }

    const fullText = allTextParts.join(" ");

    // 1. Check forbidden absolute claims
    const absolutePhrases = [
      /100%\s*(đạt|thành công|hiệu quả)/i,
      /chắc chắn\s*(đạt giải|thành công)/i,
      /tối ưu nhất/i,
      /hoàn hảo nhất/i,
      /triệt để 100%/i,
      /đảm bảo giải nhất/i,
    ];

    for (const regex of absolutePhrases) {
      if (regex.test(fullText)) {
        violations.push(`Phát hiện khẳng định tuyệt đối không có căn cứ: "${regex.source}"`);
      }
    }

    // 2. Check fabricated student counts or class sizes (e.g. "42 học sinh", "sĩ số 45")
    const classSizeRegex = /(\d{2,3})\s*(học sinh|em học sinh|hs|sĩ số)/gi;
    const matches = fullText.match(classSizeRegex);
    if (matches) {
      for (const m of matches) {
        const numStr = m.match(/\d+/)?.[0];
        // If this specific number is not in knownFacts, reject as fabricated
        const knownText = JSON.stringify(knownFacts);
        if (numStr && !knownText.includes(numStr)) {
          violations.push(`Phát hiện số liệu sĩ số/học sinh tự sinh không có trong hồ sơ: "${m}"`);
        }
      }
    }

    // 3. Check for specific fake percentage statistics (e.g. "tăng 85.5%", "đạt 92%")
    const percentRegex = /(\d{1,3}(?:[.,]\d+)?)\s*%/g;
    const percentMatches = fullText.match(percentRegex);
    if (percentMatches) {
      for (const p of percentMatches) {
        const knownText = JSON.stringify(knownFacts);
        if (!knownText.includes(p)) {
          violations.push(`Phát hiện số liệu phần trăm tự sinh không có trong hồ sơ: "${p}"`);
        }
      }
    }

    // 4. Check maximum title length constraint
    if (output.action === "analyze_topic") {
      for (const s of output.suggestions) {
        if (s.title.length > 300) {
          violations.push(`Tên đề tài vượt quá giới hạn 300 ký tự: "${s.title.substring(0, 30)}..."`);
        }
      }
    } else if (output.action === "suggest_topics") {
      for (const t of output.topics) {
        if (t.title.length > 300) {
          violations.push(`Tên đề tài vượt quá giới hạn 300 ký tự: "${t.title.substring(0, 30)}..."`);
        }
      }
    }

    return {
      pass: violations.length === 0,
      violations,
    };
  }
}
